vti_encoding:SR|utf8-nl
vti_author:SR|HP\\Gary
vti_modifiedby:SR|HP\\Gary
vti_timelastmodified:TR|08 Mar 2010 15:08:00 -0000
vti_timecreated:TR|05 Feb 2010 05:24:21 -0000
vti_extenderversion:SR|6.0.2.8161
vti_backlinkinfo:VX|DetailTrade.asp DetailTrade1.asp
vti_nexttolasttimemodified:TW|05 Feb 2010 06:06:41 -0000
vti_cacheddtm:TX|08 Mar 2010 15:08:00 -0000
vti_filesize:IR|33873
vti_cachedbodystyle:SR|<body leftmargin="8" topmargin="8" OnLoad="document.fm1.submitted.value=0;" onkeypress="return disableCtrlKeyCombination(event);" onkeydown="return disableCtrlKeyCombination(event);" >
vti_cachedlinkinfo:VX|Q|include/uob.css H|javascript:window.print() H|javascript:window.doConvert() H|javascript:ordersubmit(<%\\ call\\ OrderVariable("TRADEDATE")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("TRADENO")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("STATUS")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("CLIENTCODE")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("CLIENTNAME")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("MARKET")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("TRADINGCCY")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("INSTRUMENT")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("INSTRUMENTName")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("BUYSELL")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("TTLQTY")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("PRICE")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("CONSIDERATION")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("BROKERAGERATE")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE1")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("SETTLEDATE")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("SETTLEDATE")\\ \\ %>) H|javascript:ordersubmit(<%\\ 'call\\ OrderVariable("")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("SETFXAMOUNT")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE2")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE3")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE4")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE5")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE6")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE7")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE8")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("a")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("b")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("REBATEAMOUNT")\\ \\ %>) H|javascript:ordersubmit(<%\\ call\\ OrderVariable("CONFIRMATIONDATE")\\ \\ %>) S|images/tel.gif
vti_cachedsvcrellinks:VX|FQUS|include/uob.css SHUS|javascript:window.print() SHUS|javascript:window.doConvert() SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("TRADEDATE")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("TRADENO")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("STATUS")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("CLIENTCODE")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("CLIENTNAME")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("MARKET")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("TRADINGCCY")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("INSTRUMENT")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("INSTRUMENTName")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("BUYSELL")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("TTLQTY")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("PRICE")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("CONSIDERATION")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("BROKERAGERATE")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE1")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("SETTLEDATE")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("SETTLEDATE")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ 'call\\ OrderVariable("")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("SETFXAMOUNT")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE2")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE3")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE4")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE5")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE6")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE7")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("ORFEE8")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("a")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("b")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("REBATEAMOUNT")\\ \\ %>) SHUS|javascript:ordersubmit(<%\\ call\\ OrderVariable("CONFIRMATIONDATE")\\ \\ %>) FSUS|images/tel.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=big5
vti_charset:SR|big5
